export const BUCHHOLZ = 'BUCHHOLZ';
export const MEDIAN_BUCHHOLZ = 'MEDIAN_BUCHHOLZ';
export const SONNEBORN_BERGER = 'SONNEBORN_BERGER';
export const PROGRESSIVE_SCORE = 'PROGRESSIVE_SCORE';
export const SCORE_GROUP = 'SCORE_GROUP';
export const RATING_BASED = 'RATING_BASED';

export const swissConstants = {
  BUCHHOLZ,
  MEDIAN_BUCHHOLZ,
  PROGRESSIVE_SCORE,
  RATING_BASED,
  SCORE_GROUP,
  SONNEBORN_BERGER,
};
