module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Competition Factory',
      items: [
        'introduction',
        'data-standards',
        'time-capsule',
        {
          'TMX Example': [
            'tmx',
            'tmx/overview',
            'tmx/participants',
            'tmx/events-categories',
            'tmx/draws',
            'tmx/matchups',
            'tmx/venues-scheduling',
            'tmx/browser-console',
            'tmx/factory-server',
            'tmx/tmx-api-surface',
          ],
        },
        'installation',
        'acknowledgements',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          Participants: ['concepts/participants', 'concepts/participant-context', 'concepts/scaleItems'],
        },
        'concepts/registration-profile',
        'concepts/tournament-tier',
        {
          Policies: [
            'concepts/policies',
            'policies/roundRobinTallyPolicy',
            'policies/tallyPolicy',
            'policies/avoidance',
            'policies/positionActions',
            'policies/positioningSeeds',
            'policies/matchUpActions',
            'policies/roundNaming',
            'policies/participantPolicy',
            'policies/seedingPolicy',
            'policies/feedInPolicy',
            'policies/feedPolicy',
            'policies/maxParticipants',
            'policies/scheduling',
            'policies/scoringPolicy',
            'policies/draws',
            'policies/rankingPolicy',
            'policies/progressionPolicy',
            'policies/consolationPolicy',
            'policies/competitiveBands',
            'policies/competitionPolicy',
            'policies/sanctioningPolicy',
            'policies/printPolicy',
          ],
        },
        {
          Events: [
            'concepts/events/events-overview',
            'concepts/events/categories',
            'concepts/events/entries',
            'concepts/events/flights',
          ],
        },
        {
          Draws: [
            'concepts/draws-overview',
            'concepts/draw-types',
            {
              type: 'category',
              label: 'Draw Type Details',
              collapsed: true,
              items: [
                'concepts/draw-types/single-elimination',
                'concepts/draw-types/double-elimination',
                'concepts/draw-types/round-robin',
                'concepts/draw-types/round-robin-with-playoff',
                'concepts/draw-types/compass',
                'concepts/draw-types/olympic',
                'concepts/draw-types/feed-in',
                'concepts/draw-types/consolation-draws',
                'concepts/draw-types/ad-hoc',
                'concepts/draw-types/drawmatic',
                'concepts/draw-types/page-playoff',
                'concepts/draw-types/playoff',
                'concepts/draw-types/lucky-draw',
                'concepts/draw-types/adaptive',
                'concepts/draw-types/swiss',
              ],
            },
            'concepts/draw-links',
            'concepts/draft-draws',
            'concepts/seed-withdrawal-cascade',
            'concepts/exit-profiles',
            'concepts/finishing-positions',
            'concepts/actions',
          ],
        },
        {
          matchUps: [
            'concepts/matchup-overview',
            'concepts/matchup-context',
            'concepts/matchup-filtering',
            'concepts/tieMatchUp',
            'concepts/lineUp',
            'concepts/tieFormat',
          ],
        },
        {
          Scheduling: [
            'concepts/scheduling-overview',
            'concepts/venues-courts',
            'concepts/scheduling-policy',
            'concepts/scheduling-profile',
            'concepts/automated-scheduling',
            'concepts/pro-scheduling',
            'concepts/scheduling-conflicts',
          ],
        },
        'concepts/date-time-handling',
        {
          Publishing: [
            'concepts/publishing/publishing-overview',
            'concepts/publishing/publishing-events',
            'concepts/publishing/publishing-seeding',
            'concepts/publishing/publishing-order-of-play',
            'concepts/publishing/publishing-participants',
            'concepts/publishing/publishing-embargo',
            'concepts/publishing/publishing-data-subscriptions',
            'concepts/publishing/publishing-workflows',
          ],
        },
        'concepts/mutation-locks',
      ],
    },
    {
      type: 'category',
      label: 'State Engines',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'engines/state-engines',
        },
        'engines/engine-methods',
        'engines/engine-logging',
        'engines/engine-middleware',
        'engines/mutation-engines',
        'engines/subscriptions',
        'engines/custom-engines',
        'engines/global-state',
        {
          type: 'category',
          label: 'Scale Engine',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'scale-engine/scale-engine-overview',
            },
            'scale-engine/scale-engine-api',
            'scale-engine/ranking-points-pipeline',
            'scale-engine/quality-win-points',
            'scale-engine/aggregation',
          ],
        },
        {
          type: 'category',
          label: 'Scoring Engine',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'scoring-engine/scoring-engine-overview',
            },
            'scoring-engine/scoring-engine-api',
            'scoring-engine/event-handlers',
            'scoring-engine/format-support',
            'scoring-engine/visualization-applications',
          ],
        },
        {
          type: 'category',
          label: 'Temporal Engine',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'temporal-engine/temporal-engine-overview',
            },
            'temporal-engine/temporal-engine-api',
            'temporal-engine/event-system-and-validation',
            'temporal-engine/block-types-and-algorithms',
            'temporal-engine/ui-integration-scenarios',
          ],
        },
        {
          type: 'category',
          label: 'Draw Engine',
          items: ['engines/draw-engine-overview', 'apis/draw-engine-api'],
        },
        {
          type: 'category',
          label: 'Sanctioning Engine',
          items: ['engines/sanctioning-engine', 'engines/sanctioning-engine-design'],
        },
        {
          type: 'category',
          label: 'Officiating Engine',
          items: ['engines/officiating-engine'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Governors',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'governors/governors-overview',
        },
        'governors/competition-governor',
        'governors/draws-governor',
        'governors/entries-governor',
        'governors/event-governor',
        {
          type: 'category',
          label: 'Generation Governor',
          items: [
            'governors/generation-governor',
            'governors/generation/generateDrawDefinition',
            'governors/generation/drawMatic',
            'governors/generation/remapDrawDefinitionMatchUpIds',
          ],
        },
        'governors/matchup-governor',
        'governors/matchup-format-governor',
        'governors/mocks-governor',
        'governors/participant-governor',
        'governors/policy-governor',
        'governors/publishing-governor',
        'governors/query-governor',
        'governors/ranking-governor',
        'governors/report-governor',
        'governors/schedule-governor',
        'governors/score-governor',
        'governors/tie-format-governor',
        'governors/officiating-governor',
        'governors/sanctioning-governor',
        'governors/tournament-governor',
        'governors/venue-governor',
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'tools/tools-overview',
        },
        'tools/make-deep-copy',
        'tools/structure-sort',
        'tools/json-to-csv',
        'tools/tools-api',
      ],
    },
    {
      Testing: [
        { type: 'doc', label: 'Overview', id: 'testing/testing-overview' },
        {
          type: 'category',
          label: 'mocksEngine',
          collapsed: false,
          items: [
            'testing/mocks-engine-overview',
            'testing/mocks-engine-getting-started',
            'testing/mocks-engine-tournament-generation',
            'testing/mocks-engine-participants',
            'testing/mocks-engine-outcomes',
            'testing/mocks-engine-league-profiles',
            'testing/mocks-engine-patterns',
          ],
        },
        'testing/factory-server',
      ],
    },
    {
      type: 'category',
      label: 'Data',
      items: [
        'constants',
        {
          Codes: ['codes/age-category', 'codes/matchup-format'],
        },
        'types/typedefs',
        'concepts/accessors',
        'concepts/timeItems',
        'concepts/extensions',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      items: ['migration'],
    },
  ],
};
